describe('Los estudiantes register', function() {
    it('Creates new account and logins successfully', function() {
      const accName = Math.floor(Math.random()*1000000);
      cy.visit('https://losestudiantes.co')
      cy.contains('Cerrar').click()
      cy.contains('Ingresar').click()
      cy.get('.cajaSignUp').find('input[name="nombre"]').click().type("Test")
      cy.get('.cajaSignUp').find('input[name="apellido"]').click().type("Testing")
      cy.get('.cajaSignUp').find('input[name="correo"]').click().type(accName + "@diegorbaquero.com")
      cy.get('.cajaSignUp').find('select[name="idDepartamento"]').select("3")
      cy.get('.cajaSignUp').find('input[name="password"]').click().type("mipassword123")
      cy.get('.cajaSignUp').find('input[name="acepta"]').check()
      cy.get('.cajaSignUp').contains('Registrarse').click()
      cy.contains('Registro exitoso!')
      cy.contains('OK').click()
      cy.get('#cuenta').click()
      cy.contains('Salir').click()
      cy.contains('Ingresar').click()
      cy.get('.cajaLogIn').find('input[name="correo"]').click().type(accName + "@diegorbaquero.com")
      cy.get('.cajaLogIn').find('input[name="password"]').click().type("mipassword123")
      cy.get('.cajaLogIn').contains('Ingresar').click()
      cy.contains('Salir')
    })
    it('Fails to created previously registered accounts', function() {
      cy.visit('https://losestudiantes.co')
      cy.contains('Cerrar').click()
      cy.contains('Ingresar').click()
      cy.get('.cajaSignUp').find('input[name="nombre"]').click().type("Test")
      cy.get('.cajaSignUp').find('input[name="apellido"]').click().type("Testing")
      cy.get('.cajaSignUp').find('input[name="correo"]').click().type("pruebasauto@diegorbaquero.com")
      cy.get('.cajaSignUp').find('select[name="idDepartamento"]').select("3")
      cy.get('.cajaSignUp').find('input[name="password"]').click().type("mipassword123")
      cy.get('.cajaSignUp').find('input[name="acepta"]').check()
      cy.get('.cajaSignUp').contains('Registrarse').click()
      cy.contains('Ya existe un usuario registrado')
    })
})
